### ISSUE TITLE
error on compiling

### ISSUE THREAD

**Issue by creeds1** [vm03/android_device_lge_w3ds#2]
Install: /home/bbq/cm/out/target/product/w3ds/system/framework/qcom.fmradio.jar
target SharedLib: libwebviewchromium (/home/bbq/cm/out/target/product/w3ds/obj/SHARED_LIBRARIES/libwebviewchromium_intermediates/LINKED/libwebviewchromium.so)
collect2: error: ld terminated with signal 9 [Killed]
build/core/shared_library.mk:81: recipe for target '/home/bbq/cm/out/target/product/w3ds/obj/SHARED_LIBRARIES/libwebviewchromium_intermediates/LINKED/libwebviewchromium.so' failed
make: **\* [/home/bbq/cm/out/target/product/w3ds/obj/SHARED_LIBRARIES/libwebviewchromium_intermediates/LINKED/libwebviewchromium.so] Error 1

**Comment by vm03** [comment]
ld terminated with signal 9
Not enough RAM for build.

**Comment by creeds1** [comment]
i need from more swap ok
but this
build/core/shared_library.mk:81: recipe for target '/home/bbq/cm/out/target/product/w3ds/obj/SHARED_LIBRARIES/libwebviewchromium_intermediates/LINKED/libwebviewchromium.so' failed
make: **\* [/home/bbq/cm/out/target/product/w3ds/obj/SHARED_LIBRARIES/libwebviewchromium_intermediates/LINKED/libwebviewchromium.so] Error 1

**Comment by vm03** [comment]
it depend from previous error
